import { Inter } from 'next/font/google';
import "./globals.css";
import Header from "./component/Header";
import Providers from "./Providers";

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: "My App",
  description: "Generated by TambalTech",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={inter.className}
      >
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
